### ISSUE TITLE
Document on-prem https deploys

### ISSUE THREAD

**Issue by josegonzalez** [plotly/dash-docs#102]
As discussed on slack, it appears we don't have docs for on-prem https deploys. We should definitely have these for customers.

Feel free to ask in the on-prem room for how it should work so it gets documented correctly :)

/cc @cldougl @bcd @chriddyp

**Comment by cldougl** [comment]
ah looks like @BRONSOLO updated the onpremise install instructions:
https://github.com/plotly/streambed/issues/10933 so we can add [that section](https://docs.google.com/document/d/1OcKeSVRHFufu1jlplyP7SQ3exn9rhVO_OaakubdwCck/edit#heading=h.7gxvtsqsh8jx) to the [dash-docs](https://dash.plot.ly/deployment/on-premise) as well.  

@josegonzalez are there any limitations to which users can use the https method or should this now be the primary recommended method?

**Comment by josegonzalez** [comment]
I don't know if the plotly.com stuff supports `https` remotes, but there is still the discoverability component of the https setup. I defer to @scjody in that case.

**Comment by bcdunbar** [comment]
https documentation was added in https://github.com/plotly/dash-docs/pull/136
