### ISSUE TITLE
Clean up the Dash tutorial

### ISSUE THREAD

**Issue by MatthewChatham** [plotly/dash-docs#105]
I've been learning Dash over the past couple of weeks, mostly using the official tutorial at https://dash.plot.ly/.

I'd like to improve the tutorial as follows:
1. Correct the part-numbering. Currently the page linked above lists 6 parts to the tutorial. However, the tutorial pages themselves are misnumbered. This should be an easy fix. I would also like to remove the section included in the first few tutorial parts, in the image below, because it doesn't match the structure of the tutorial as listed on the main page of the User Guide:

![image](https://user-images.githubusercontent.com/18629176/41595914-668ed03c-737d-11e8-9ee4-ea3f1f0c604a.png)

2. Add a page for the excellent style guide currently hosted here: https://codepen.io/chriddyp/full/bWLwgP/. Personally, I am still unclear on whether I need to link to any external CSS to make use of Dash's grid system, so we should probably address that on the style guide page.

Lastly, and this is unrelated, but I have noticed that pages frequently load at the bottom or middle of pages rather than the top in the User Guide. Is there a known reason for this? Is it fixable? I found it annoying and would hate for others to miss the great tutorial on Dash's website if they're also experiencing it.

**Comment by chriddyp** [comment]
@MatthewChatham 
1 - Page Numbering: Yup, that'd be a good fix. I'd also be OK with just removing that section.
2 - A dedicated page on this styleguide would be great, including examples of how to use the grid and columns, how to link the CSS, and how to customize it. @ned2 was thinking of working on something like this as well.
3 - Links - Yeah, it's a known issue. There's an issue for it here: https://github.com/plotly/dash-core-components/issues/99

Feel free to make a PR to fix those issues, I'll 👍

**Comment by MatthewChatham** [comment]
Thanks @chriddyp , I'll make a PR this week!

**Comment by ned2** [comment]
I think 1) is now resolved and  3) was fixed with plotly/dash-core-components/pull/215. 

I've opened up a dedicated issue for 2) at #166.
