### ISSUE TITLE
callback context not working in case I am using dcc.upload

### ISSUE THREAD

**Issue by adityakumar04** [plotly/dash-docs#1061]
Hi, 

I am using multiple elements in a page and all elements operate within nested loops. Inside the loop I first upload a file using dcc.upload and then use callback context to check when a submit button is pressed. However on using dcc.upload the callback context returns to upload file and never goes inside the submit button callback context. Attached is a loop output which will help you understand the problem. 

Refer to the image - after "all done" I have initalized  
ctx = dash.callback_context                                         
print(ctx.triggered[0]['prop_id'].split('.')[0])
if ctx.triggered[0]['prop_id'].split('.')[0] == 'hive':[](url)

<img width="173" alt="Screenshot 2020-12-23 at 2 53 46 PM" src="https://user-images.githubusercontent.com/64469406/102981508-11d6c780-452f-11eb-8840-9df113c26f67.png">

**Comment by alexcjohnson** [comment]
Closing - I'll comment on https://github.com/plotly/dash/issues/1510
