### ISSUE TITLE
CI Docs for Pull Requests & Review Apps

### ISSUE THREAD

**Issue by tobinngo** [plotly/dash-docs#1070]
# [WIP] CI Docs for Pull Requests & Review Apps 

After seeing more interest in CI/CD pipeline integration from some of our customers (via Zendesk), we have added a new doc page touching on Continuous Integration for Dash Enterprise (https://dash.plotly.com/dash-enterprise/continuous-integration). We plan to expand the document to include instructions and templates for common CI platforms and our GraphQL API(https://dash-playground.plotly.host/Docs/app-manager-api).

### Common CI platforms

- Codefresh
- Bamboo
- CircleCI
- Github
- Gitlab
- GoCD
- Jenkins
- TravisCI
- Teamcity

**Comment by chriddyp** [comment]
Now available in https://dash.plotly.com/dash-enterprise/review-apps 🎉
