### ISSUE TITLE
Python class example in React for Python guide should pass self instead of this

### ISSUE THREAD

**Issue by DrGFreeman** [plotly/dash-docs#1088]
The Python class example in the [React for Python Developers](https://dash.plotly.com/react-for-python-developers) guide should pass `self` to the `render` method instead of `this`.

https://github.com/plotly/dash-docs/blob/097ffa75f4ee662de1c6f58ee8229696673b2607/dash_docs/chapters/react_for_python_developers/index.py#L356

Also, this may be my ignorance with respect to JavaScript but shouldn't the `init` method in the JS class example take `a` as an argument?

https://github.com/plotly/dash-docs/blob/097ffa75f4ee662de1c6f58ee8229696673b2607/dash_docs/chapters/react_for_python_developers/index.py#L363-L366

Finally, there are two apparent differences between the two class examples:
1. The Python class passes `a` to the parent class' `__init__` method whereas in the JS class example, `super()` is called without arguments.
2. The Python class example assigns `self.a = a` before calling the parent class' `__init__` method whereas in the JS class example, the order is the opposite (probably not significant).

I can submit a PR following feedback on the different items above.

🚀 Great guide BTW!

**Comment by alexcjohnson** [comment]
@DrGFreeman good eye! You're right about all of the above.
1. since `a` is used in the subclass, it shouldn't go in either `super()` call.
2. unlikely to matter in practice but you're right to bring it up, no reason to muddle things. Let's put the superclass constructor first in both cases, that's the more standard pattern.

**Comment by DrGFreeman** [comment]
@alexcjohnson, thanks for the feedback. I'll update PR #1089 with the additional changes tonight.
