### ISSUE TITLE
[small bug fix] add quotes to a word in the client side callbacks example

### ISSUE THREAD

**Issue by yasserius** [plotly/dash-docs#1137]
In [this file](https://github.com/yasserius/dash-docs/blob/485140256e627136076ab2a2dde0f1dd7f65e089/dash_docs/chapters/clientside_callbacks/examples/graph_update_fe_be_px.py#L82), line 82:

`...figure.layout.yaxis, type: scale`

should be

`...figure.layout.yaxis, 'type': scale`

I would have sent a pull request if I could figure out the branching stuff, but couldn't. Hope this helps! thanks!

**Comment by alexcjohnson** [comment]
Ah yeah, we mixed conventions there, thanks!. That code is JS, not Python, so in fact the quotes are unnecessary (unless the key is an invalid JS identifier). We should remove them from the object keys throughout that example.

**Comment by yasserius** [comment]
It was causing errors on my site, and the quotes fixed it, so I posted an issue. Thanks!
