### ISSUE TITLE
Update Link in documentation

### ISSUE THREAD

**Issue by yesdeepakmittal** [plotly/dash-docs#1176]
![image](https://user-images.githubusercontent.com/50262096/142646512-99ffe4ef-08d5-4ff1-aeae-f1cc2a9d2642.png)
In "_More Slider Examples and Reference_", the underlined link is forwarding to the **dropdown example** page instead of the **slider example** page

**Comment by LiamConnors** [comment]
Thanks @yesdeepakmittal for reporting this! We've fixed it and we'll deploy the update soon.
