### ISSUE TITLE
Examples with `trigger_id = ctx.triggered[0]["prop_id"].split(".")[0]` potentially misleading as command only gets the first trigger

### ISSUE THREAD

**Issue by JonThom** [plotly/dash-docs#1177]
In [Advanced Callbacks](https://dash.plotly.com/advanced-callbacks) and likely elsewhere, the examples show the use of 

```
trigger_id = ctx.triggered[0]["prop_id"].split(".")[0]
```

The docs should make clear that this command only gets the id of the first triggered input (due to `ctx.triggered[0]`). In fact, it would be better to advise users to do

```
trigger_ids = [triggered["prop_id"].split(".")[0] for triggered in ctx.triggered]
```

**Comment by red-patience** [comment]
Hey there, thanks for the issue. We'd actually like to go beyond that and rework this syntax to make it easier to use and understand. I recommend following along [here](https://github.com/plotly/dash/issues/1054). Bit of an old issue but one that we're still keeping our eyes on!
