### ISSUE TITLE
Coiled + Dash + Dask example is out of date

### ISSUE THREAD

**Issue by scharlottej13** [plotly/dash-docs#1212]
👋 Thanks for all your work on Dash, it's a really nice data viz tool.

I work for Coiled and noticed the existing example in the docs is pretty out of date https://dash.plotly.com/dask-dash-coiled. I'd like to update it, but am having trouble finding it in this repo. From the readme, it seems like it could be in https://github.com/plotly/ddk-dash-docs, but I can't see this repo.

Would someone be able to point me in the right direction?

Thanks!

**Comment by alexcjohnson** [comment]
Hi @scharlottej13 - thanks for reaching out! Yes, unfortunately (for external contributors) we moved dash docs to a closed-source repo. If the changes needed are straightforward you can describe them here and we’ll adapt them to our code. If they’re more involved we’d be happy to set up a call, in that case please email me at alex@plot.ly.

FYI @LiamConnors

**Comment by scharlottej13** [comment]
Thanks @alexcjohnson!

Theses are the changes I'm proposing:
- update the dask logo on the card under "extended ecosystem" on https://dash.plotly.com/ ([here's an option](https://github.com/dask/dask/blob/2b45b215e13e6d7893853ef33cb4b1796c477a9e/docs/source/images/dask_icon.svg), more in repo)
- remove https://dash.plotly.com/dask-dash-coiled
- edit https://dash.plotly.com/dask-dash#dash-+-dask-on-a-cluster to:
```diff
This arrangement separates scalability needs at the front end with the scalability needs of the back end, leading to more efficient use of resources.

+ There are a number of ways you can run Dask on a cluster including:
+ - [Coiled](https://www.coiled.io/?utm_source=dash-docs&utm_medium=dash-dask)
+ - [Dask Kubernetes](https://kubernetes.dask.org/en/latest/operator.html)
+ - [Dask Cloud Provider](https://cloudprovider.dask.org/en/latest/)
+
+ See the [Dask documentation](https://docs.dask.org/en/stable/deploying.html#distributed-computing) for more details.
```

Happy to hop on a call and and discuss if you'd like.

cc @jrbourbeau

**Comment by LiamConnors** [comment]
Thanks @scharlottej13! I've made the updates. Another thing I noticed when going through the page at `/dask-dash` is that we link out to a notebook that is no longer available. So I swapped out this link that appears in the introduction https://github.com/dask/dask-tutorial/blob/main/04_dataframe.ipynb to https://github.com/dask/dask-tutorial/blob/main/01_dataframe.ipynb - that seems like the new version.

You can take a look at a preview here: https://test-dash-docs-dask-updates-da9e259cacd8.herokuapp.com/dask-dash
Let me know what you think and I'll update this on the live site.

**Comment by scharlottej13** [comment]
>  I've made that update and the change is live now.

Thanks @LiamConnors!

> For the original content that was there at https://dash.plotly.com/dask-dash-coiled, I'm curious about how much of the content was out of date.

The vast majority of the original content was out of date on that page, it was mostly prose that was restated from our docs at that time. 

> Do you think longer term there would be some value in a new updated page that provides info on Coiled specifically?

Talking to the rest of the team, I don't think this is a priority at the moment, but perhaps in the future!

**Comment by LiamConnors** [comment]
Thanks for the feedback! Will close out the issue.
