### ISSUE TITLE
Document the tabs component

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-docs#127]
Now that tabs are released, it's time to update our user guide with some examples 🎉 

See https://github.com/plotly/dash-docs/pull/123 for a similar set of files that will need to be updated.

For the examples, I like to:
- Include a bare bones example for the index page: https://dash.plot.ly/dash-core-components/. Basically including only the props that you need.
- In the "Examples and Reference" link for the page (it'll be https://dash.plot.ly/dash-core-components/Tabs), include several useful examples with some text explaining them and, for the first couple of examples, callbacks tying it all together. https://dash.plot.ly/dash-core-components/dropdown is a good example
- In all of the examples, I try to make them useful and aesthetically pleasing/inspiring

For tabs, I think these examples would be useful:
- Explaining the inline content vs content in a callback and clearly explaining the tradeoffs (loading all of the content vs loading it on the fly)
- An example overriding the colors with some other nice colors
- An example changing the style from full-width tabs to GitHub style tabs (as I attempted to do in the original PR)

And then we'll want to include the reference table for both the `Tabs` component and the `Tab` component.

**Comment by valentijnnieman** [comment]
Because #183 is now merged, I think we can close this issue!
