### ISSUE TITLE
example of `n_clicks_timestamp` for button

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-docs#138]
The button example:
![image](https://user-images.githubusercontent.com/1280389/44039649-80ebcd0a-9ee7-11e8-89de-66c24f1c83b9.png)

Could use a page of its own, like the rest of the components. In that page, we should include an example of `n_clicks_timestamp` (see the forum for examples)

**Comment by michaelbabyn** [comment]
closed by #219
