### ISSUE TITLE
revert the revert

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-docs#157]
these commits https://github.com/plotly/dash-docs/compare/1b9688a6...8570fb0b were recently reverted by @nicolaskruchten . Apparently they broke the docs on master

**Comment by nicolaskruchten** [comment]
Oh I didn't revert them! I rolled back the Heroku deploy is all :)

**Comment by T4rk1n** [comment]
I had removed the server import from `tutorial.run` when I refactored the imports because it was greyish in my editor (unused). Fixed in #159.
