### ISSUE TITLE
External resources docs need to include using __name__ as name parameter

### ISSUE THREAD

**Issue by davidolmo** [plotly/dash-docs#168]
As stated [here](https://community.plot.ly/t/dash-app-does-not-load-assets-and-app-index-string/12178/5), the [External resources docs](https://dash.plot.ly/external-resources) need to include the explanation that it is needed to add `__name__` in order to make Dash recognize as local resources the files (css, favicon...) inside the assets folder

A good dash initialization would be:
`app = dash.Dash(name=__name__)`

**Comment by T4rk1n** [comment]
I think all examples should have `app = dash.Dash(__name__)`.

**Comment by michaelbabyn** [comment]
closed by #198
