### ISSUE TITLE
Layout as a function.

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash-docs#172]
I haven't seen this feature mentioned in the docs. Basically, we let users assign a function as layout, this function can then dynamically create the layout depending on some other variables. I think it's a great feature for more advanced users and we should document it somewhere.

There's a few caveats that should be mentioned when dealing with this feature.

- The layout function will be called before the first requests, meaning if you want to use `flask.requests` you will have to check if you actually have the request context.
- The initial layout should return the whole layout with all the components that are used in callbacks or set `app.config.suppress_callback_exceptions = True`.

**Comment by rmarren1** [comment]
It is mentioned at the bottom of this: https://dash.plot.ly/live-updates

**Comment by T4rk1n** [comment]
I see, I was expecting to see it in the dash layout section https://dash.plot.ly/getting-started.

I think it would still be good to include a warning about the callback exceptions.

**Comment by ned2** [comment]
I could add an entry to the FAQ (#146)

Something like: "How can I create dynamic page layouts?"

perhaps?

**Comment by michaelbabyn** [comment]
@T4rk1n , do you think this is addressed between https://dash.plot.ly/live-updates and the [new dash faq](https://dash.plot.ly/faqs) talking about callbacks in the layout?

> ## Callbacks require their Inputs, States, and Output to be present in the layout
> By default, Dash applies validation to your callbacks, which performs checks such as validating the types of callback arguments and checking to see whether the specified Input and Output components actually have the specified properties. For full validation, all components within your callback must therefore appear in the initial layout of your app, and you will see an error if they do not.
> However, in the case of more complex Dash apps that involve dynamic modification of the layout (such as multi-page apps), not every component appearing in your callbacks will be included in the initial layout. You can remove this restriction by disabling callback validation like this:
> app.config.supress_callback_exceptions = True

**Comment by T4rk1n** [comment]
I think we should add a better example to the one in live-updates. Something that verify if it got the request context and return a whole layout if not.

I personally don't like to set `suppress_callback_exception` and prefer to not rely on it, so a valid pattern example where it isn't needed would be a good addition.

You can check if you have the request context with `flask.has_request_context()`.

**Comment by michaelbabyn** [comment]
closed by #201
