### ISSUE TITLE
Cannot Run Locally

### ISSUE THREAD

**Issue by jdamiba** [plotly/dash-docs#190]
When I follow the instructions in the Readme, I get the following error:

`ModuleNotFoundError: No module named 'tutorial.run'`

Here is a screenshot of my IDE with versions of my python, virtualenv, and gunicorn. I am on a 2017 MacBook Pro with macOS High Sierra (Version 10.13.6).

<img width="1440" alt="screen shot 2018-09-17 at 9 44 48 am" src="https://user-images.githubusercontent.com/1557650/45626843-7e181600-ba5e-11e8-93cd-1db5e5f2ec59.png">

**Comment by chriddyp** [comment]
Related https://github.com/plotly/dash-docs/pull/188

It looks like you're using Python 3. The instructions say that you should use Python 2, but that could be more obvious. Try using Python 2.

**Comment by jdamiba** [comment]
Having switched to Python 2.7, I get a slightly different error:
`ImportError: No module named run`

<img width="1440" alt="screen shot 2018-09-17 at 10 25 23 am" src="https://user-images.githubusercontent.com/1557650/45629319-1ebd0480-ba64-11e8-98d3-ee43452aac2a.png">

If I run `gunicorn run:server` instead of `gunicorn tutorial.run:server` (since there is a run.py file in the root directory but not in the tutorial directory), I get a more involved error:

`ImportError: cannot import name compare_digest`

<img width="1440" alt="screen shot 2018-09-17 at 10 28 26 am" src="https://user-images.githubusercontent.com/1557650/45629429-6e033500-ba64-11e8-892a-c06fc6b9e4f4.png">

**Comment by chriddyp** [comment]
Hm, that's odd. I deleted my virtualenv and reinstalled from `requirements.txt` and the `gunicorn` command succeeded.

**Comment by chriddyp** [comment]
OK, looking into the history, it looks like `gunicorn tutoria.run:server` is actually outdated. `gunicorn run:server` is the right command, sorry about that 🙈 

For the `hmac` issue, I found https://stackoverflow.com/questions/26535043/. I'm running `python 2.7.10` and it works for me, perhaps your version of 2.7 is too old?

**Comment by jdamiba** [comment]
Using Python 2.7.10 rather than 2.7 worked for me.
