### ISSUE TITLE
replace append_script and append_css with `external_scripts` and `external_stylesheets`

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-docs#193]
We'd like to eventually remove `app.css.append_css`. We've created new methods for including local and remote css (https://github.com/plotly/dash/pull/286) and we should update all of our examples to use these new methods instead of `append_css`. 

The new way to include remote and local assets are documented here: https://dash.plot.ly/external-resources. We should replace `append_css` with `external_stylesheets=[...]` everywhere

**Comment by michaelbabyn** [comment]
closed by #198
