### ISSUE TITLE
Create a component page out of date?

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-docs#205]
I was reading https://dash.plot.ly/plugins and it seems to me it's a bit out of date now that we generate materialized Python files and not JSON descriptors, right?

**Comment by rmarren1** [comment]
I think this line can be updated:
> The Python component package includes the JSON file and the JavaScript bundle as extra files through the MANIFEST.in file.

It still contains the `metadata.json` file, but the package will include a Python class for each component.

**Comment by nicolaskruchten** [comment]
I think it's actually worth stressing a bit that all Python code is autogenerated, so that you don't have to do it, but you *can* inspect it afterwards if you want. @VeraZab and I were trying to figure out how to confirm that once a prop was added to the React component, it had been picked up in the Python. The only ways I could think of were to check the generated Python (which isn't mentioned here) or to "try to use that prop in an app" but the former seems better :)

**Comment by rmarren1** [comment]
What about modifying this paragraph? I think the word _dynamically_ is no longer relevant, and when talking about the Python classes we should let users know how to build them and where to find them.

> Dash reads this JSON file and ~dynamically~ **automatically** ~creates~ **generates** Python classes that subclass a core Dash component. These classes include argument validation, Python docstrings, types, and a basic set of methods. **You can inspect these files by checking in the folder with your component suite name (e.g. the `dash_html_components` folder) after running `npm run build:py`.** ~These classes are generated entirely automatically.~ A JavaScript developer does not need to write any Python in order to generate a component that can be used in the Dash ecosystem.

**Comment by T4rk1n** [comment]
> Also, how does the build process work actually?

`metadata.json` is generated by the `extract-meta` js file, then generate_class use that to generate the python classes from the `metadata.json`.

Working to make the dash-component-boilerplate a cookiecutter currently. From my changes, we only need to run `build:all` and it will generate everything (js min/dev bundles, metadata, python classes). It's worth noting that dash needs to be installed in the python env to run the `build:py` command, I've added it to the boilerplate readme.

**Comment by nicolaskruchten** [comment]
If the JSON file is only used to generate classes, is it even worth mentioning in this doc?

**Comment by T4rk1n** [comment]
I think if someone wants to know how it works it should still be mentioned, but the process is now transparent with the `build:py` command and we don't read the metadata.json file at runtime anymore.
