### ISSUE TITLE
Changing the favicon

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash-docs#208]
We should add more information on how to change the favicon, right now we only tell that we look for a favicon in the assets folder. But now that we have a default favicon we should be more explicit:

- A default favicon is provided if no `favicon.ico` is found in the assets folder.
- To override the default favicon you need to put `favicon.ico` in the assets folder, there is no other way.
- Changes to the favicon in the assets folder will bust the favicon cache.

**Comment by joseangel-sc** [comment]
I want to point out to whoever has the problems I was having... this: 

```
@app.server.route('/favicon.ico')
def favicon():
    return flask.send_from_directory(os.path.join(app.server.root_path, 'static'),
                                     'favicon.ico', mimetype='image/x-icon')

```

Is no longer working, while it was a problem for me, after paying attention the important part that @T4rk1n  mentions is that it *has* to be in a folder named "assets" if you do that it works like magic
