### ISSUE TITLE
Document the dcc.Store

### ISSUE THREAD

**Issue by T4rk1n** [plotly/dash-docs#213]

**Comment by chriddyp** [comment]
We should document this in two places:
1. An entry in `dash.plot.ly/dash-core-components` like the rest of the components
2. Update the examples in https://dash.plot.ly/sharing-data-between-callbacks, replacing "hidden div" with `dcc.Store`
   - In addition, we should emphasize that this is "New in version ..." and mention something like:
> Previously, we used hidden divs. Now we have a first class component for holding data in the browser front-end: `dcc.Store`. There are a few things to note:
> - Unlike the hidden div method, `dcc.Store` holds the data in the browser's memory instead of rendering it to the browser's DOM.
> - With this method, the data is still getting transferred to the browser. So, do not store any secret data in `dcc.Store`.
> - Unlike the hidden div method, you do not need to `json.dumps` your data, Dash will do it automatically for you.

**Comment by chriddyp** [comment]
> Is Store a reactive event source?

It's a component like all of the other components, so you can use it's properties as `Input`, `Output`, or `State` and updating properties of the component will trigger callbacks.

**Comment by brylie** [comment]
Ok, so any property of dcc.Store will be reactive, or specific properties? Looking forward to reading the docs :-)

**Comment by irmavdbrandt** [comment]
Hi @chriddyp ,

When do you expect to have the documentation about the dcc.Store component ready?
Or could you post an example how to use it?
I would really like to incorporate it in my dashboard but find it hard to do so without an example.

**Comment by T4rk1n** [comment]
@irmavdbrandt

I am working on the docs today, expect a PR by the end of the day. In the meantime, I posted a couple examples in the announcement thread:

https://community.plot.ly/t/announcing-the-storage-component/13758

There's a bug found yesterday, fix should be out soon:

https://github.com/plotly/dash-core-components/pull/333

**Comment by irmavdbrandt** [comment]
Thank you very much @T4rk1n! :)

**Comment by bcorrea1** [comment]
Hi! im having an issue with DCC Store component (or maybe i guess that is my problem). Im using Dcc Store to save data from a file and use it when its needed without the need of reloading the file. The thing is when i run it in my computer it works well, but when i deploy it in a flask app, the callbacks asociated to the dcc.store component stop responding. what could be the problem?

**Comment by Akronix** [comment]
@bcorrea1 i don't know how to solve your problem, but you might get better answers asking it in the plotly forum for dash: https://community.plot.ly
