### ISSUE TITLE
Document multi-file structure for Dash projects

### ISSUE THREAD

**Issue by brylie** [plotly/dash-docs#244]
Issue moved from: https://github.com/plotly/dash-recipes/issues/19

The Dash guide shows how to create a Dash app in a single file, and a basic example of a [multi-page project with separate files](https://dash.plot.ly/urls). However, each app file quickly grows to several hundred files for a moderately sized dashboard (i.e. when layout and callbacks are combined in a single file). 

The question of how to organize Dash apps, so that callbacks are in a separate file, has been raised several times in the Dash community forum. 

Lets add a recipe for how to break down a Dash app into separate files, as can be seen in the Dash [slapdash boilerplate](https://github.com/ned2/slapdash/tree/master/src/slapdash). The Slapdash project is well-designed, but does not explain **why** the files are structured in such a way and **how** to create a simple Dash project with that file structure.

**Comment by ned2** [comment]
I describe the motivation for the architecture of Slapdash in [this forum post](https://community.plot.ly/t/splitting-callback-definitions-in-multiple-files/10583/2?u=nedned), explaining in particular why there is both a `server.py` and an `app.py` module so as to avoid circular imports. This particular aspect was modelled directly off the layout of the [Dash Docs](https://github.com/plotly/dash-docs) code. 

I'm thinking that I might actually prefer the approach taken in the section of the docs on [Structuring a Multi-Page App](https://dash.plot.ly/urls) which has an `index.py` that is the entry point of the app and which also includes the routing logic. But that's more of an aside. The difference in Slapdash that you're concerned with is that callbacks and layouts are in different files. However, so long as you've managed the circular imports, that part is actually fairly straightforward.

**Comment by brylie** [comment]
@ned2, I made some progress on the project layout section. Please review the work-in-progress:

https://dash-docs-pr-245.herokuapp.com/project-structure

Comments are welcome here or in PR #245

**Comment by brylie** [comment]
@ned2 the PR is ready for review.

**Comment by ned2** [comment]
Just started looking at, but don't have heaps of free time at the moment,
so will have some feedback in the next day or two :)
