### ISSUE TITLE
Broken image on data tables in gallery

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-docs#257]
From https://dash.plot.ly/gallery

![image](https://user-images.githubusercontent.com/203523/48136019-96d9c680-e26c-11e8-9a3e-fec53edcbf59.png)

**Comment by xhlulu** [comment]
@matthewchan15

**Comment by matthewchan15** [comment]
@xhlulu sure

**Comment by xhlulu** [comment]
Sorry I meant in the PR where you change all the herokuapp links, not the lastodash
