### ISSUE TITLE
DashR Docs

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-docs#263]
Placeholder

**Comment by rpkyle** [comment]
Following discussion with @chriddyp, need to begin assembling Dash Docs written in DashR and served via DDS. Draft plan (slightly more advanced placeholder, subject to change):

- Aim for release by mid-February
- Manually create DashR docs that are very close to the content and level of
detail and quality found in current Dash for Python online documentation
- Begin by creating index page with link to Part 3 chapter on callbacks, then draft that content first.
- In essence, successful documentation will comprise four pieces:

- [ ] Multipage app
- [ ] Handwritten copy
- [ ] Autogenerated examples, which execute R code live
- [ ] Live interactive demos derived from that R code

**Comment by rpkyle** [comment]
Closing as the intitial documentation is available online at https://dashr.plot.ly.
