### ISSUE TITLE
Broken image for lastodash

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-docs#284]
@matthewchan15 I think you posted this right?

![image](https://user-images.githubusercontent.com/203523/48740207-850d0180-ec24-11e8-919a-f013723cc61e.png)

**Comment by matthewchan15** [comment]
Hey @nicolaskruchten I did post this https://github.com/plotly/dash-docs/pull/264/files. Looks like the `img_src` went stale!
