### ISSUE TITLE
Add an example of table virtualization

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-docs#299]

**Comment by chriddyp** [comment]
@Marc-Andre-Rivet - could you fill this in a little bit with the properties or syntax? that'll make it easier for other folks to fill out the examples.

**Comment by chriddyp** [comment]
alternatively, link to a integration test if one exists?

**Comment by michaelbabyn** [comment]
duplicate of #339. This will be resolved by #341
