### ISSUE TITLE
Wind Speed Measurement Application redirects to wrong app in Dash Gallery

### ISSUE THREAD

**Issue by matthewchan15** [plotly/dash-docs#312]
In the [Dash Gallery](https://dash.plot.ly/gallery), the Wind Speed Measurement Application is redirecting to https://dash-gallery.plotly.host/dash-yield-curve when it should be redirecting to https://dash-gallery.plotly.host/dash-wind-stream.

**Comment by constantlycoding** [comment]
This is already fixed by 7e4a3e741f7b333d5315eb782e71ddf4463a8e68.
