### ISSUE TITLE
CircleCI gives timeout error 

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-docs#359]
CI tests sometimes fail with the following message, even if the demo app on Heroku works fine (seen in #350): 

```
======================================================================
ERROR: test_docs (tests.test_integration.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_integration.py", line 126, in test_docs
    visit_and_snapshot(link)
  File "tests/test_integration.py", line 119, in visit_and_snapshot
    self.wait_for_element_by_id('wait-for-page-{}'.format(href))
  File "tests/test_integration.py", line 43, in wait_for_element_by_id
    wait_for(find_element_by_id)
  File "tests/utils.py", line 61, in wait_for
    raise WaitForTimeout(get_message())
WaitForTimeout

----------------------------------------------------------------------
Ran 1 test in 112.681s

FAILED (errors=1)
Exited with code 1
```

**Comment by xhlulu** [comment]
Getting the same error. Could this have to do with Percy snapshots?

**Comment by shammamah** [comment]
The demo apps (and the docs themselves) show as "Application error" for a while after being deployed, and then they start working again, so I think it's something to do with the docs themselves being too large to load quickly (especially since it started after adding Dash DAQ, which was a significant addition).

**Comment by xhlulu** [comment]
This is interesting. Would it be better to schedule merging during low traffic hours in this case? Considering the amount of people visiting the docs we might want to minimize redeployment downtime, depending on how long this is.

**Comment by cldougl** [comment]
closing in favour of https://github.com/plotly/dash-docs/issues/377
