### ISSUE TITLE
Uncaught TypeError with dash-cytoscape docs (ref. #353)

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-docs#364]
## Version

* Python 2.7
* Everything is in requirements.txt

## Description

In the Dash Cytoscape PR (#353), an `Uncaught TypeError` appears whenever we hover over or click an element. This seems to be related to props `tapNode, tapEdge, mouseoverNodeData`, etc. Uncommitted changes seem to show that those props do not fire callbacks when they are nested inside in a `_chapter.py` file (using `tools.load_example` or `Display`). 

This error does not happen when the app is run on its own.

Link to WIP app: https://dash-docs-pr-353.herokuapp.com/cytoscape

## Console Error

The following error appears in the console, when you manipulate a cytoscape graph:
```
Uncaught TypeError: n is not a function
    at e.exports.<anonymous> (bundle.js?v=0.0.2&m=1547436153:1)
    at o (bundle.js?v=0.0.2&m=1547436153:6)
    at bundle.js?v=0.0.2&m=1547436153:6
    at bundle.js?v=0.0.2&m=1547436153:6
    at u.l.emit.l.trigger (bundle.js?v=0.0.2&m=1547436153:6)
    at l.emit (bundle.js?v=0.0.2&m=1547436153:15)
    at bundle.js?v=0.0.2&m=1547436153:6
    at bundle.js?v=0.0.2&m=1547436153:6
    at u.l.emit.l.trigger (bundle.js?v=0.0.2&m=1547436153:6)
    at e.exports.emit (bundle.js?v=0.0.2&m=1547436153:13)
```

## Examples

Nested inside a chapter (broken): 
https://github.com/plotly/dash-docs/blob/b2a8ab2e3b35483ac625a0df0214e21a41dffe38/tutorial/cytoscape/elements_chapter.py#L247-L257

Standalone (working): 
https://github.com/plotly/dash-docs/blob/b2a8ab2e3b35483ac625a0df0214e21a41dffe38/tutorial/examples/cytoscape/compound.py

**Comment by cldougl** [comment]
![capture](https://user-images.githubusercontent.com/2789078/51350622-a2b8e480-1a76-11e9-96be-3edd4eb9c13d.PNG)

**Comment by chriddyp** [comment]
Things to check:
- Run it in dev mode locally so that the error isn't minified and then update the issue with a screenshot of the error
- sometimes this can be an issue with partially defined callback IDS: the input of a callback might be visible on a page (triggering the callback) but the other inputs or the output isn't. In Dash, either _all_ IDs need to be visible or _none_ of them. So, double check your IDs

**Comment by xhlulu** [comment]
By dev mode you mean running this? 
```python
if __name__ == '__main__':
    app.run_server(debug=True, threaded=True, port=8060)
```

For visible IDs, is it across a single page, or the entire dash-docs?

**Comment by xhlulu** [comment]
## Unminified error message
Tthe unminified error (which I activated after refactoring the project) shows `Uncaught TypeError: setProps is not a function` instead of `Uncaught TypeError: n is not a function`.

## Problem

In the react component wrapper, we have an event listener to the cytoscape component that updates the `mouseoverEdgeData` prop whenever the user clicks a node in the graph. The code used be written like this:
```JavaScript
cy.on('mouseover', 'edge', event => {
    if (setProps !== null) {
        setProps({
            mouseoverEdgeData: event.target.data()
        })
    }
});
```
which doesn't catch undefined setProps. and is likely the reason why we have the error above.

## Solution

The exact problem is this: setProps is undefined when the component is not used as an input to a callback (such as in this situation). this is why I set a condition where setProps is only fired if its type is a "function". I was able to fix it by running this:
```JavaScript
cy.on('mouseover', 'edge', event => {
    if (typeof setProps === 'function') {
        setProps({
            mouseoverEdgeData: event.target.data()
        })
    }
});
```

## Next step

The problem described where I am unable to dump the json output of `mouseoverEdgeData`, or any prop generated by a user interaction event, is still persisting. I need to go deeper to find out the exact cause of this problem.

**Comment by xhlulu** [comment]
I have a suspicion that this might be caused by how `cy.on(...)` is binding to the Cytoscape object. I am still working on trying to reproduce this. If anyone has an idea please let me know.

**Comment by xhlulu** [comment]
I think I've narrowed down the problem to this:
![cytoscape problem](https://user-images.githubusercontent.com/21180505/51409568-2edb1280-1b30-11e9-9284-d4d3f1116bee.PNG)

(Sorry for the small image). In this example, I assigned a callback to this component such that, whenever the component is clicked, we update the `tapNodeData` prop using `setProps`. However, here `setProps` is undefined, which is not supposed to happen. In comparison, when the same app is run standalone, we get this (same breakpoint as the previous image):

![problem solved](https://user-images.githubusercontent.com/21180505/51409807-d7897200-1b30-11e9-9775-266490440fd4.PNG)

Which shows that setProps is defined as a function. This example also correctly dumps the `tapNodeData`.

If we can figure out why `setProps` is undefined here then this issue should be straighforward to solve.

**Comment by xhlulu** [comment]
@cldougl @chriddyp lmk your thoughts

**Comment by T4rk1n** [comment]
`setProps` is undefined on dash-docs because it is not present in the initial layout, when such is the case, the component only get `setProps` later in the lifecycle (ie: not in `componentDidMount`).

Consider moving the `const { setProps } = this.props` inside the on callback.

**Comment by xhlulu** [comment]
@T4rk1n yes, this solved it! Thanks @T4rk1n @chriddyp. Please check out https://github.com/plotly/dash-cytoscape/pull/28
