### ISSUE TITLE
Joystick not included in docs

### ISSUE THREAD

**Issue by shammamah** [plotly/dash-docs#369]
There is a `Joystick` component in the `dash-daq` repository, but it’s not mentioned here: https://dash-daq.netlify.com and not in the dash daq docs that are part of dash.plot.ly.

**Comment by nicolaskruchten** [comment]
Yeah, the Netlify doc gen system wasn't compatible with Joystick.

**Comment by xhlulu** [comment]
@shammamah Feel free to follow https://github.com/plotly/dash-docs/issues/364 where i'm logging my issues with Cytoscape props not firing callbacks.

**Comment by shammamah** [comment]
Closed in #370.
