### ISSUE TITLE
dds doc on dealing with DDS relative URLs vs local URLs

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-docs#371]
when the app is deployed on DDS, it has a URL prefix (the app name). This requires the dev to modify some things in their app. We should have a doc page that explains this:
- How to provide relative links to assets like images
- How to deal with `dcc.Location` urls for developing on localhost and on DDS (normalize the pathname by stripping out the app name at the start of the function)
- How to provide `dcc.Link` or `html.A` links
- In general, how to check if the app is running in a DDS environ (`is 'DASH_APP_NAME' in os.environ`)

I end up writing a utils function that I use everywhere like:
```python
def relpath(path):
    """
    Prefix relative URLs with the Dash app name in case that
    the app is deployed on DDS.
    """
    if 'DASH_APP_NAME' in os.environ:
        return '/{}{}'.format(os.environ['DASH_APP_NAME'], path)
    return path
```

we should include this function in the docs

**Comment by ned2** [comment]
The other context where this sort thing is relevant is registering URLs for multipage apps. When defining a route -> page layouts mapping for the `dcc.Location` callback that functions as the router, you need to prefix the route with `ROUTES_PATHNAME_PREFIX`. I write a very simple helper function like your `relpath` @chriddyp. 

It had occurred to me that Dash could have a `get_path_url` that functions analogously to the `get_asset_url` that does this. If this were implemented, it could also take care of prefixing `DASH_APP_NAME` if it's set (on top of `ROUTES_PATHNAME_PREFIX` as they're going to need to stack).

**Comment by cldougl** [comment]
closing in favour of https://github.com/plotly/dash-core/issues/201
