### ISSUE TITLE
update pdf service doc 

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-docs#393]
https://dash.plot.ly/dash-deployment-server/pdf-service 
`POST https://<your-plotly-enterprise-server>/api/dash-apps/image`
should be updated to 
`POST https://<your-dash-deployment-server>/Manager/api/generate_report`

**Comment by chriddyp** [comment]
Let's also update the authentication methods & where to find the secret keys

**Comment by cldougl** [comment]
```
{
    "url": "...",
    "appname": os.environ.get('DASH_APP_NAME'),
    "secret_key": os.environ.get('DASH_SECRET_KEY'),
    "format": "pdf",
    "pdf_options": {
        "pageSize": "Letter",
        "marginsType": 1
    },
    "wait_selector": "body"
}
```
