### ISSUE TITLE
spike - improvement on visual regression

### ISSUE THREAD

**Issue by byronz** [plotly/dash-docs#417]
the current *percy* visual regression has several issues in terms of execution time and false alert(noise):

1. the snapshot is mostly taken at the top level of each chapter route, which produces a super long snapshot image. it's not obvious to catch the minor diff
2. there are some hardcoded `time.sleep(5)` which should be replaced by implicit_wait 
3. there is no easy way to ignore certain flakey area by either css selector or fixed region coordinates, need to investigate more on percy docs, or trial on **applitools**
4. lack of IE testings, @cldougl mentioned ideally we should test at least the last two *edge* versions

@plotly/dash-core comments are welcome

- [x] change the datetime.now() case in demo   #423 #425 
- [x] reduce the execution time with `driver.implicitly_wait(2)  #427

**Comment by alexcjohnson** [comment]
most of the flaky areas, as far as I've seen, come from using `datetime.now()`. We should just replace that with a fixed value like `datetime(2019, 2, 26, 12, 0, 0, 0)`. More verbose but at least deterministic!

**Comment by xhlulu** [comment]
Percy is currenly unable to render canvas element, since it is not part of the DOM. Enabling JS when taking the snapshot does not seem to solve the problem. If you visit the actual page, you can see that there's a network where the blank box is: https://dash.plot.ly/cytoscape

Here's what the Percy snapshot looks like:
![image](https://storage.googleapis.com/percy-images/03d3ecab93251bccc005c60b5d6fb838dc41e25c34744cb5072f5c3cf6e31506)

**Comment by wbrgss** [comment]
Re: canvas elements, this is what the Percy Dev told me (excepted from a longer conversation...):

> 02:06 PM | Robert from Percy: Just wanted to let you know I've been throwing stuff at the wall over here with my python to try and get something working and I haven't quite yet either. 
> 
> 02:07 PM | Will Burgess: OK, thanks, I really appreciate it. Unfortunately the product (Dash) uses Python/React to render content and its method of serving assets (with Flask) is a bit complicated
> 
> 02:09 PM | Will Burgess: I am close to getting something that's "good enough", but two main problems I have are 1.) nested DOM elements are rendered out of order and 2.) html <canvas> elements don't render properly
> 
> 02:11 PM | Robert from Percy: Ohhh, nested DOM elements being rendered out of order is really interesting. Is there any CSS (flexbox) that changes their order visually? 
> 
> 02:11 PM | Will Burgess: yeah for sure
> 
> 02:12 PM | Robert from Percy: Canvas would be expected since that's not serialized to the DOM -- you could enable JS (if the JS files are present) and it should draw the canvas element
> 
> 02:12 PM | Robert from Percy: I have a little script that converts canvas elements to base64 images before taking the DOM snapshots for our newer SDKs. 
> 
> 02:13 PM | Will Burgess: Oh interesting
> 
> 02:14 PM | Robert from Percy: This is what that looks like https://gist.github.com/Robdel12/151cac2f92adebc18c8693ea3d252581
> 
> 02:14 PM | Robert from Percy: I'd be curious if there would be a way to adapt that
> 
> 02:15 PM | Will Burgess: Yeah, that looks like it could be done with Selenium
> 
>

**Comment by wbrgss** [comment]
There's also another tool (asset discovery) that hasn't been added to the Python SDK yet, but is in the Percy pipeline

**Comment by alexcjohnson** [comment]
Oh interesting indeed - I was about to suggest converting to an image actually, we've done similar stuff in plotly.js to push webgl output to a static image. Some of the other repos have a `percy_snapshot` method in their `IntegrationTests` inherited class, if this works we should just build it in there; convert every `<canvas>` to an `<img>`, take the snapshot, then remove the `<img>` tags and put `<canvas>` back where it was.

Enabling JS is unlikely to be useful, that'll only be able to run things that happen on page load.

**Comment by xhlulu** [comment]
Is there any way to recommend feature for Percy? It would be so much
simpler to be given the option to use the webdriver screenshot method
rather than their optimized DOM loading method.

**Comment by wbrgss** [comment]
@xhlulu I'm pretty sure the "DOM snapshots" are a core part of the product
> [Using DOM snapshots] is very intentional---we want to keep your environment fast and handle all the complexities of deterministic rendering and visual diffs in our infrastructure

(https://docs.percy.io/docs/faq)

The Python SDK is arguably outdated and is being actively worked on. The Percy dev I talked to suggested using Puppeteer, but I don't think that will solve our `<canvas>` problem. I'm interested in making the canvas to image script, as this is the last thing that's missing from my tests in Dash Design Kit.

**Comment by alexcjohnson** [comment]
The new page navigation menu has increased the Percy noise a good deal - we either need to wait longer so it's finalized before we take the snapshot, or we should hide that menu from Percy.

We also need a solution for the iterative dash-bio components,  that keep moving just a little bit for many seconds. Again, either we need to find a way to make them repeatable or we need to remove them.

**Comment by wbrgss** [comment]
In another project (plotly/dash-design-kit#680, private repo) @markzporter used [Percy-specific CSS](https://docs.percy.io/docs/percy-specific-css) to add `visibility: hidden` to the problematic elements, with a `visibility: visible` pseudo-element that indicated the hidden element should be ignored in manual review of Percy snapshots.
