### ISSUE TITLE
Small issue with a graduated bar example

### ISSUE THREAD

**Issue by YunkeXiao** [plotly/dash-docs#445]
Hey, theres' a small issue with the showCurrentValue example in the GraduatedBar page I think; the bar isn't filled properly. It works properly when implemented though.
![graduated_bar_issue](https://user-images.githubusercontent.com/33202018/54647784-4a07c700-4a7a-11e9-8bbf-6931a76539d4.png)

**Comment by ycaokris** [comment]
It shows properly now as I see in the master branch.

<img width="883" alt="Screen Shot 2019-03-25 at 3 16 23 PM" src="https://user-images.githubusercontent.com/35306149/54947556-fc270f00-4f10-11e9-8729-7bb7eb7b98c4.png">
