### ISSUE TITLE
dds - update directory mapping documentation 

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-docs#447]
update https://dash.plot.ly/dash-deployment-server/map-local-directories according to https://github.com/plotly/streambed/issues/11833

**Comment by joaoalf** [comment]
Here are the screenshots:
![Screenshot from 2019-03-28 17-51-08](https://user-images.githubusercontent.com/840120/55195173-23384780-5182-11e9-96c7-fc65b8cc5535.png)

![Screenshot from 2019-03-28 17-53-46](https://user-images.githubusercontent.com/840120/55195368-bc675e00-5182-11e9-878e-ccbc716f1c96.png)

Pleaase let me know if you need more material.

**Comment by joaoalf** [comment]
@cldougl We're moving the field away from the customizations section. Please hold until I update the settings screenshot.

**Comment by joaoalf** [comment]
Here's the updated settings screenshot:
<img width="832" alt="Capture d’écran, le 2019-04-02 à 12 59 14" src="https://user-images.githubusercontent.com/840120/55417627-7413bb80-5547-11e9-8454-cc2b52d5f851.png">

You can move on.
