### ISSUE TITLE
Console errors found on datatable page

### ISSUE THREAD

**Issue by ycaokris** [plotly/dash-docs#481]
Multiple console errors were catched on https://dash.plot.ly/datatable

<img width="1075" alt="Screen Shot 2019-04-26 at 11 41 05 AM" src="https://user-images.githubusercontent.com/35306149/56819695-45bc8f80-6818-11e9-91bb-a2961b1cd6a2.png">

**Comment by byronz** [comment]
@ycaokris  the fix in #482 corrected the first error. the second error is interesting, it's an id `annot-canvas` defined in a separated python app, but not found in the parent/referring layout as we get the ids from store paths. this bug should be reported on dash-renderer
