### ISSUE TITLE
Switch from githubusercontent to local assets

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-docs#486]
Edit: as discussed below, the even better solution, now that we've gotten rid of the `github.com/.../raw` links, is probably to put all of these into local assets instead.

-----
We have a number of links (to images mostly if not entirely) that the page requests from `github.com/plotly/dash-docs/raw`, for example

https://github.com/plotly/dash-docs/blob/5616c8211a8fe19346a26d1f9ffbbe276f82e89d/assets/override.css#L8

Github automatically redirects these to `raw.githubusercontent.com` but this can introduce a fairly long delay. Elsewhere we use `githubusercontent` directly, we should convert the remaining links.

**Comment by nicolaskruchten** [comment]
Why not use the assets directory?

**Comment by alexcjohnson** [comment]
Yes, we could certainly switch to assets, and that has advantages like docs would work offline.

**Comment by alexcjohnson** [comment]
The change to local assets is a bigger project - so I merged #526 in order to get the immediate benefit of removing those redirects, but I'll leave this issue open with a revised name.

**Comment by nicolaskruchten** [comment]
Why is it a bigger project? Seems to work fine for the logo change I made last week...?

**Comment by alexcjohnson** [comment]
Easy, just tedious - a lot of files new files for `assets`, and a lot more changes than just the 8 or 9 links needed for the original issue.

```
MacBook-Pro-6:dash-docs alex$ ag -l githubusercontent
tutorial/core_components.py
tutorial/auth.py
tutorial/on_premise_deployment.py
tutorial/dashbio.py
tutorial/sharing_state.py
tutorial/dashbio_component_examples.py
tutorial/core_component_examples.py
tutorial/utils/dashbio_docs.py
tutorial/graphing.py
tutorial/external_css_and_js.py
tutorial/table/editing_recipes_chapter.py
tutorial/examples/getting_started_crossfilter.py
tutorial/examples/getting_started_table.py
tutorial/examples/walmart.py
tutorial/examples/graph_callbacks_crossfiltering.py
tutorial/examples/getting_started_viz.py
tutorial/examples/getting_started_multiple_viz.py
tutorial/examples/dashbio_components/speck.py
tutorial/examples/dashbio_components/volcano_plot.py
tutorial/examples/dashbio_components/needle_plot.py
tutorial/examples/dashbio_components/circos.py
tutorial/examples/dashbio_components/molecule_3d_viewer.py
tutorial/examples/dashbio_components/manhattan_plot.py
tutorial/examples/dashbio_components/alignment_chart.py
tutorial/examples/dashbio_components/onco_print.py
tutorial/examples/dashbio_components/clustergram.py
tutorial/examples/graph_callbacks_same_graph.py
tutorial/examples/table/callbacks_sorting_filtering.py
tutorial/examples/table/callbacks_paging_and_sorting.py
tutorial/examples/table/interactivity_connected_to_graph.py
tutorial/examples/table/interactivity_simple.py
tutorial/examples/table/filtering_be.py
tutorial/examples/table/interactivity_row_ids.py
tutorial/examples/table/virtualization.py
tutorial/examples/table/callbacks_paging_multicolumn_sorting.py
tutorial/examples/table/callbacks_paging.py
tutorial/examples/table/filtering_fe.py
tutorial/examples/table/callbacks_filtering_graph.py
tutorial/examples/table/simple.py
tutorial/examples/table/callbacks_filtering.py
tutorial/examples/getting_started_graph.py
tutorial/examples/core_components/store_share.py
tutorial/urls.py
assets/override.css
```

**Comment by wbrgss** [comment]
FYI I think most if not all of these CSVs are now in `/assets` (at least, at the time of writing, I had to add another recently in #782). So the docs run in an airgapped environment thanks to @chriddyp's changes in https://github.com/plotly/dash-docs/commit/819c5898 that find and replaces these `githubusercontent` URLs.

So if we want to remove those URLs entirely (and not just replace them at runtime) I think his commit is a good place to start

**Comment by wbrgss** [comment]
I think we got all of the images too in #783. I might have missed one or two..

**Comment by chriddyp** [comment]
I think we want to keep the external CSV links for our end users so that it's easy to copy and paste examples. The rest of the assets have been moved. So I'd consider this one closed
