### ISSUE TITLE
Add preventUpdate to the docs 

### ISSUE THREAD

**Issue by alinastarkov** [plotly/dash-docs#495]
It took me a while to dig through the community forum to find it, i think it might be useful to people if we add a section about how to abort / skip callback to the FAQ section: https://github.com/plotly/dash/pull/190

**Comment by alexcjohnson** [comment]
Yes, this really needs some docs... https://community.plot.ly/t/how-to-selectively-update-outputs-in-callback-i-e-update-some-not-all-for-an-error-message-implementation/27046/2
