### ISSUE TITLE
add doc detail on portal & dash app auth levels

### ISSUE THREAD

**Issue by matthewchan15** [plotly/dash-docs#498]
Suggestion by @jackparmer to add more details about authentication levels (authenticated, unauthenticated, and restricted), with regards to both the portal and Dash apps.

There should be a clear concise description of how each authentication level affects users, and the difference between portal and Dash application authentication.

Currently the information we have is lacking: https://dash.plot.ly/dash-deployment-server/privacy
https://dash.plot.ly/dash-deployment-server

I created a very in-depth slide show I can send you @michaelbabyn to help you crush this out!

**Comment by michaelbabyn** [comment]
Hey @matthewchan15 ,  If you could send me that slide show / let me know what other details you'd like to see in there that would be great. I remember thinking that the UI was pretty clear so any extra info will be useful.

**Comment by bpostlethwaite** [comment]
@michaelbabyn can we close?
