### ISSUE TITLE
Not all callbacks functional in Part 5 of Dash Cytoscape docs

### ISSUE THREAD

**Issue by ohaanika** [plotly/dash-docs#551]
# Problem

Not all callbacks appear to be functional in [**Part 5. Event Callbacks for User Interactions**](https://dash.plot.ly/cytoscape/events), specifically in the first two sections, **Simple callback construction** and **Click, tap and hover**.

# Potential Cause

Since all three `cytoscape` graphs in Part 5 have the same `id='cytoscape-event-callbacks'`, the callbacks divided between the three sections are retrieving input data from the most recently declared graph (i.e. the third graph) instead of the intended graphs. 

# Potential Solution

Relabel each `cytoscape` graph and respective callbacks to have `id='cytoscape-event-callbacks-i'` for `i={1,2,3}`.

**Comment by ohaanika** [comment]
Solution implemented, tested and pushed to branch: https://github.com/plotly/dash-docs/tree/dash-cytoscape/tutorial

**Comment by rpkyle** [comment]
#552 merged (thanks @ohaanika!) so closing this stale issue.
