### ISSUE TITLE
Dedicated datatable tooltips example

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/dash-docs#558]
See [this code](https://github.com/plotly/dash-table/blob/6721d03ae3bda1836ec157e097bdc4648b28bd59/demo/AppMode.ts#L130-L171) for reference.

**Comment by rpkyle** [comment]
@michaelbabyn Did this ever happen? If not, I try to help get this added this to the Python side at the same time we take care of the R example.

**Comment by michaelbabyn** [comment]
@rpkyle , I don't believe this has been added yet.

**Comment by chriddyp** [comment]
This is documented implicitly in the conditional formatting chapter but it could still use its own chapter for quick reference. Should include:
- How to style the tooltips with CSS
- Conditional tooltips - tooltips on some cells but not others. Include a recommendation for how to style those cells to indicate that there is a tooltip (a dotted underline)
- Including images in tooltips if that's possible
- Copy over the example from conditional tooltips that shows how to use them if your text is abbreviated

**Comment by Marc-Andre-Rivet** [comment]
@michaelbabyn Should be closed by https://github.com/plotly/dash-docs/pull/1001 (docs link: http://dash.plotly.com/datatable/tooltips)
