### ISSUE TITLE
add search for dashr docs 

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-docs#570]
- [ ] add back search link in header 
- [ ] make URLs consistent across python and r docs
- [x] create an algolia search index for dashr (similar to python: https://github.com/plotly/dash-docs/blob/master/dash_search_index.py)
- [ ] create dashr search landing page (similar to: https://github.com/plotly/dash-docs/blob/master/tutorial/search.py)

**Comment by cldougl** [comment]
first pass at dashr-doc algolia index: https://www.algolia.com/apps/7EK9KHJW8M/explorer/browse/dashr_docs

**Comment by jdamiba** [comment]
closed by https://github.com/plotly/dash-docs/pull/769
