### ISSUE TITLE
prettify from jsonlite library used without being imported

### ISSUE THREAD

**Issue by michaelbabyn** [plotly/dash-docs#577]
Callbacks from the first example on https://dashr.plot.ly/graph-crossfiltering fail with `error: could not find function "prettify"` unless I import the jsonlite package by adding `library(jsonlite)` to the top of the example.

**Comment by CanerIrfanoglu** [comment]
Just added `library(jsonlite)` to this example in `dashr-squashed`. Docs should be updated once the branch is merged to the master.

@michaelbabyn Hope we can close this issue now? :)

**Comment by HammadTheOne** [comment]
Fixed in updated deployment of docs. Example is fully functional now. 

https://dashr.plot.ly/interactive-graphing

Thanks @CanerIrfanoglu 

Closing.
