### ISSUE TITLE
Standardizing URL Naming Conventions

### ISSUE THREAD

**Issue by ohaanika** [plotly/dash-docs#584]
While matching the urls for R docs, I had a question about url naming conventions for Python docs.

I see that for Component Libraries in the Python version, the name convention isn't consistent, for example:
- Dash HTML Components --> https://dash.plot.ly/dash-html-components
- Dash Cytoscape --> https://dash.plot.ly/cytoscape
- Dash Canvas --> https://dash.plot.ly/canvas
- Dash Bio --> https://dash.plot.ly/dash-bio

I personally felt it should either have `dash-` before `html-components`, `canvas`, `cytoscape`, `bio` or not at all.

Is this something we want to standardize for Python docs?

While @shammamah @rpkyle agree, they pointed reasons we might not want to change urls for Python docs, one being that some people have these URLs saved (but that we can easily just add a redirect to those specific pages that points to the correct standardized url).

For now, I will simply match the R docs to have the same URLs as the Python docs as is. If any changes are made later, it can be reflected for both docs at that time.

@chriddyp @nicolaskruchten, your input would be appreciated!

**Comment by chriddyp** [comment]
These have now been standardized to be the component library name
