### ISSUE TITLE
docs - DataTable `max-height` sizing style not respected

### ISSUE THREAD

**Issue by Marc-Andre-Rivet** [plotly/dash-docs#603]
https://dash.plot.ly/datatable/sizing

This table should scroll / max out in size at 300px.
Tried this locally in isolation and it worked fine. Not sure what's going on.

![image](https://user-images.githubusercontent.com/8092993/61252612-15f09a00-a72c-11e9-9e55-5cb178dd6023.png)

**Comment by chriddyp** [comment]
Should be fixed in https://github.com/plotly/dash-docs/pull/847
