### ISSUE TITLE
use `dcc.Store` in the sharing-data-between-callbacks chapter

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-docs#605]
https://dash.plot.ly/sharing-data-between-callbacks still describes the hidden div solution - we should update this to `dcc.Store`

**Comment by emmanuelle** [comment]
:+1:

**Comment by alexcjohnson** [comment]
keeps coming up https://community.plot.ly/t/difference-in-sharing-data-between-callbacks-with-hidden-divs-and-dcc-store/31448
