### ISSUE TITLE
Merge DashR docs into master

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-docs#640]
Right now the DashR docs are in the `dashr-squashed` branch, but in an ideal world they'd be on `master`, with auto-deployment to the dashr.plot.ly site.

**Comment by lundstrj** [comment]
Sorry guys. I did not mean to unassign you.

**Comment by rpkyle** [comment]
This issue was resolved when plotly/dash-docs#674 was merged. Closing now.
