### ISSUE TITLE
More prominent callback_context docs

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-docs#668]
`dash.callback_context` is currently only documented in the FAQ - it deserves more prominent placement - perhaps in [Part 4. More About Callbacks](https://dash.plot.ly/state)?

We've discussed this need before, but it just came up again in https://community.plot.ly/t/callback-origin-and-reset-clickdata-on-python-dash/29805

**Comment by chriddyp** [comment]
Now in https://dash.plotly.com/advanced-callbacks
