### ISSUE TITLE
move clientside_callbacks out of performance and into it's own chapter && create a new "callbacks" section

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-docs#754]
perhaps we can have a section title that's like "Advanced Callbacks" and has the following chapters:
1. Clientside Callbacks (pull it out of performance)
2. Determining Which Input Has Changed
3. When to use a single callback vs multiple callbacks
4. Callback limitations
5. `callback_context`  (pull it out of faq) #760 
6. Describe initialization and the `is None` check

With clientside callbacks within performance, it doesn't lend itself well to searches

**Comment by chriddyp** [comment]
in the clientside callbacks chapter, let's also include an example that shows how to update a graph via the front-end and the back-end. That is:
1. Backend callback updates a store
2. Frontend callback updates the graph based off of the store and another element (like a dropdown)

With that strategy, we'd want to include two examples:
1. The store is just a dataframe, and the graph is the JSON representation of `fig`
2. The store is a `figure` generated from `plotly.express` and the frontend callback mutates the figure

the limitation of (1) is that you can't use `px` in the front-end. So, we'd want to explain the underlying figure representation and how it's constructed, linking to https://plot.ly/python/creating-and-updating-figures/ and showing how you can better understand the figure generated by px by printing it and inspecting it.

**Comment by alexcjohnson** [comment]
Clientside callback docs are actually erroneous right now, as pointed out by @chabb in https://github.com/plotly/dash/issues/1139 - the namespace is missing, should be an extra level of nesting inside `window.dash_clientside` before you get to the function itself:

> The documentation for clientside callback is incorrect. https://community.plot.ly/t/dash-0-41-0-released/22131
> 
> ```
> if(!window.dash_clientside) {window.dash_clientside = {};}
> window.dash_clientside.clientside = {
>     display: function (value) {
>         return 'Client says "' + value + '"';
>     }
> }
> ```
> 
> You have to add the namespace in the client-side code that you put in the asset folder. Something like that : 
> 
> ```
> window.dash_clientside = Object.assign({}, window.dash_clientside, {
>     clientside: {
>          highlightSegment: function(largeValue1) {
>             console.log('called with', largeValue1)
>         }
>     }
> })
> ```
> would fix it.

**Comment by Marc-Andre-Rivet** [comment]
From previous entries, I think the following structure would make sense:

Dash Tutorial Section
- extend `Basic Callbacks` to include `State`
- remove `State` from `More About Callbacks`
- remove `More About Callbacks`

Callbacks Section
- new `Callbacks` section after `Dash Tutorial`
- link to `Basic Callbacks`
- Renamed `More About Callbacks` --> `Advanced Callbacks` that includes PreventUpdate, no_update, context, initialization `is None`
- New `Inline Callbacks` Clientside callbacks that includes Clientside callbacks (assets JS file) and inline clientside callbacks with JS equivalent PreventUpdate/no_update/context

**Comment by shammamah** [comment]
Instead of creating a top-level Callbacks section, could we instead have a Callbacks section under "Beyond the basics"?

**Comment by Marc-Andre-Rivet** [comment]
@shammamah Callbacks are one of the fundamental aspects of building an app. I think it deserves its own section.

**Comment by Marc-Andre-Rivet** [comment]
Might be a good thing if we were to pull out `Memoization` from under https://dash.plot.ly/performance (only the basic memoization usage.. would leave the multi-thread/process aspect where it is) and add it under the new callbacks section. We can always add a link in `Performnce` to (1) inline callbacks, (2) callback performance.

**Comment by Marc-Andre-Rivet** [comment]
It might also be interesting to move the callbacks Gotchas (https://dash.plot.ly/faqs) under the new callbacks section.

- `All callbacks must be defined before the server starts`
- `A component/property pair can only be the Output of one callback`
- `Callbacks require all Inputs, States, and Output to be rendered on the page`
- `Callbacks require their Inputs, States, and Output to be present in the layout`
- (already mentioned) `Q: How do I determine which Input has changed?`
