### ISSUE TITLE
app lifecycle chapter or mention it in the first chapter of callbacks

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-docs#755]
explain the order in which things are called and updated:
1. When `python app.py` or `gunicorn app:server` is run, all of the files are "executed". meaning that `df = pd.read_csv('...')` is run when the program starts, rather than when the page is loaded. (so, if the CSV changes, `df` isn't updated until the program restarts. So, users should provide their data via a periodic celery task or by passing it around in a `app.layout` function)
2. `app.layout` is rendered. either the static value or the return of the function
3. `@app.callback` are fired if they exist in particular order. maybe link to a dedicated page on the callback DAG or begin describing how the DAG works here. `None` is passed if initial values aren't provided. mention that you can skip this update with `prevent_initial_call=True`
3. Some components might fire a callback once they get rendered for the first time. like `dcc.Location`. we call these "derived properties". mention which components do this. `dcc.Location.pathname` and associated properties, maybe `DataTable.derived_*` properties? Should verify
5. app waits for user interaction

**Comment by nicolaskruchten** [comment]
@jdamiba I recommend addressing this at the same time as #852
