### ISSUE TITLE
Switch URL for in docs get pricing

### ISSUE THREAD

**Issue by jingningzhang1** [plotly/dash-docs#806]
https://github.com/plotly/dash-docs/blob/2c0ead099f144904baa0da873dfbb4b25fc1357b/dash_docs/tutorial/dash_deployment_server.py#L16

@shammamah would you be able to switch the code above from https://plot.ly/dash/pricing/ to https://plot.ly/get-pricing/

FYI @VeraZab

**Comment by VeraZab** [comment]
to https://plot.ly/get-pricing/ actually, that other one does not exist

**Comment by shammamah** [comment]
This will also be undergoing the change from plot.ly to plotly.com, so I'll link #788 here to remind us to update it when the time comes.

**Comment by jingningzhang1** [comment]
thanks @shammamah!

**Comment by shammamah** [comment]
@jingningzhang1 I'm seeing some other instances of this URL: 
https://github.com/plotly/dash-docs/search?q=dash%2Fpricing&unscoped_q=dash%2Fpricing

Should I fix all of them? 

There's this one in particular that, if fixed, would have two links pointing to the same URL: https://github.com/plotly/dash-docs/blob/2c0ead099f144904baa0da873dfbb4b25fc1357b/dash_docs/tutorial/introduction.py#L35

**Comment by jingningzhang1** [comment]
@VeraZab can you please advise?

**Comment by VeraZab** [comment]
ok Sham, no need to fix them all, as like you're saying, we'll make a pass at those urls with the .com change.

i'll fix it when fixing the redirect: https://github.com/plotly/streambed/issues/14253#event-3111230016

> There's this one in particular that, if fixed, would have two links pointing to the same URL

not quite sure what you mean by that.. if we're linking too much to the same page in one paragraph, then perhaps we should revisit the text and content of that paragraph in the docs?
it even sounds like from the text of that paragraph that it should link more to: https://plot.ly/dash/app-manager/ ?

**Comment by shammamah** [comment]
>not quite sure what you mean by that..

Oh oops, sorry -- I misread `get-demo` as `get-pricing`. I can change them to the correct plot.ly URLs now and then you can change them to the .com domain when the time comes.

**Comment by VeraZab** [comment]
Ok, that sounds good, thanks Sham!
