### ISSUE TITLE
interactive graph callbacks example not working

### ISSUE THREAD

**Issue by ned2** [plotly/dash-docs#81]
The interactive graph callbacks demo example is not working in the Dash Guide. None of hover, click etc callbacks fire in both the [live version](https://dash.plot.ly/interactive-graphing) and also running locally. 

Strangely, this doesn't seem to be a problem when running `tutorial/examples/graph_callbacks_simple.py `as a standalone app outside of the tutorial.

Furthermore, the correct behaviour can be restored to the dash-docs app by downgrading to `dash_core_components==0.20.1`

**Comment by chriddyp** [comment]
Ahh, good catch! Hm... I wonder what's going on here. My guess is that https://github.com/plotly/dash-core-components/commit/e25bec2d512ecb63d022aa4943479116e199066d is the culprit.
