### ISSUE TITLE
dash for r - bullets are on a new line instead of the same line

### ISSUE THREAD

**Issue by chriddyp** [plotly/dash-docs#837]
originally reported in https://github.com/plotly/dash-docs/pull/826#pullrequestreview-385107365

![image](https://user-images.githubusercontent.com/1280389/78202726-efa19480-7449-11ea-990d-f00f47865910.png)

The R side has `<li><p></p></li>`  and the Python side has `<li></li>`. So it's likely an issue with how the markdown is formatted. We could either fix this:
1. with CSS (a selector for `li p`) or investigate the markdown string in the R side 
2. or by making the markdown string in the R docs better match the Python one
3. Or if the strings are the same, then it might be because one of the packages is outdated and might not include some kind of markdown fix that `dccMarkdown` included. Upgrading the package might help.

**Comment by Marc-Andre-Rivet** [comment]
This seems fixed. Closing.

DashR docs:
![image](https://user-images.githubusercontent.com/8092993/90190872-ce549b80-dd8d-11ea-9e54-017fddcabfe1.png)

DashPy docs:
![image](https://user-images.githubusercontent.com/8092993/90190904-e0ced500-dd8d-11ea-820f-5b1a947c52b4.png)
