### ISSUE TITLE
Sidebar width in dash docs

### ISSUE THREAD

**Issue by jingningzhang1** [plotly/dash-docs#863]
@chriddyp when you get a chance, would you be able to fix the sidebar width in the dash docs?
On some pages, like https://dash.plotly.com/layout, the ad runs off into the text. But on other pages, like the dash docs home page, the sidebar is fixed, so this not an issue.
![image](https://user-images.githubusercontent.com/50333592/80246037-c2579900-8639-11ea-83e9-12a4275cddcf.png)

**Comment by alexcjohnson** [comment]
Adding my follow-on comment from Slack:

> It’s also a strange experience when you scroll down the page a bit and the navigation links seem to be arbitrarily cut off. @chriddyp I know it was an explicit decision to not have this section sticky, can we do something like not put them in a scroll container and instead add a margin below them big enough for the ad?

<img width="416" alt="Screen Shot 2020-04-23 at 1 18 04 PM" src="https://user-images.githubusercontent.com/2678795/80249739-60e6f880-8640-11ea-881a-23306e1b930f.png">

**Comment by chriddyp** [comment]
Yeah this is a browser issue, here's how it appears in Firefox which I'm on:
![image](https://user-images.githubusercontent.com/1280389/80250027-ced2f600-8627-11ea-8a6c-5dfc028ec8e9.png)

**Comment by alexcjohnson** [comment]
To me it looks a bit better on FF, but still not quite right - at least it's not actually obscuring text, but the ad still extends outside the sidebar
<img width="455" alt="Screen Shot 2020-04-24 at 3 48 58 PM" src="https://user-images.githubusercontent.com/2678795/80251220-3b0f2300-8643-11ea-89fc-b76c48c2c0cd.png">
