### ISSUE TITLE
add prevent_initial_call

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/dash-docs#874]
https://github.com/plotly/dash/pull/1228 - to be released in Dash 1.12

`@app.callback(prevent_initial_call=True)`

`app.clientside_callback(prevent_initial_call=True)`

`app = Dash(prevent_initial_callbacks=True)` (and then setting `False` in certain callbacks)

**Comment by nicolaskruchten** [comment]
@jdamiba I recommend addressing this at the same time as #852
