### ISSUE TITLE
npm scripts in "React for Python Developers" section are out of date

### ISSUE THREAD

**Issue by jdamiba** [plotly/dash-docs#927]
In the `build the project` section, the scripts documented are different than the scripts in the `package.json` in the `dash-component-boilerplate`.

We should get rid of references to scripts that aren't there anymore and add documentation for the scripts that are there.

**Comment by Marc-Andre-Rivet** [comment]
Make sure http://dash.plotly.com/react-for-python-developers actually works :)

**Comment by jdamiba** [comment]
closed by https://github.com/plotly/dash-docs/pull/1092/
