### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by maybelinot** [plotly/dash-docs#95]
Hey there,

I was looking into [the docs](https://dash.plot.ly/) and noticed few typos [here](https://github.com/plotly/dash-docs/blob/287a7130bcf01c6cfc1fd529ab189a1c79c0fb1b/tutorial/chapter_index.py#L159-L164):
* ~styleseets~ -> stylesheets 
* ~can optionally these~ -> can host? these

Not really suitable for a PR, so feel free to include it in one of a fix commits 😃

**Comment by bpostlethwaite** [comment]
Thanks for the note. FYI it is absolutely suitable for a PR and we would definitely welcome one!
