### ISSUE TITLE
Empty/Whiteout userguide

### ISSUE THREAD

**Issue by DrakezulsMinimalism** [plotly/dash-docs#971]
The newest version of the PDF user guide (4 months old) seems to be empty/completely white despite it having 35MB in size. Opened with Chrome and Adobe Reader.
[UserGuide@Master](https://github.com/plotly/dash-docs/blob/master/pdf-docs/Dash_User_Guide_and_Documentation.pdf)

**Comment by alexcjohnson** [comment]
duplicate of #897
